spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

security:
  jwt:
    secret: 'SuXgLeIdVKvKlR4/Eq4MHRXeziSV2IR0YIUSb8NdZD4='
    ttl-seconds: 36000
